import type { AsepriteGateway } from "../../domain/aseprite.js";

export type LayerFramePort = Pick<AsepriteGateway, "createCanvas" | "addGroup" | "addLayer" | "deleteLayer" | "renameLayer" | "duplicateLayer" | "reorderLayer" | "setLayerBlendMode" | "mergeLayerDown" | "flattenSprite" | "addFrame" | "addFrames" | "setFrame" | "setFrameDuration" | "setFrameDurationAll" | "setLayerVisibility" | "setLayerOpacity" | "setPalette">;
export type DrawingPort = Pick<AsepriteGateway, "drawPixels" | "drawLine" | "drawRectangle" | "fillArea" | "drawCircle" | "drawPixelsAt" | "drawLineAt" | "drawRectangleAt" | "fillAreaAt" | "drawCircleAt" | "drawPolygon" | "drawPath" | "applyGradientRect" | "drawEllipseAt">;
export type ExportAnimationPort = Pick<AsepriteGateway, "exportSprite" | "copySprite" | "exportFrame" | "exportLayers" | "exportTag" | "importImageAsLayer" | "createCel" | "clearCel" | "copyCel" | "copyFrame" | "setCelPosition" | "tweenCelPositions" | "offsetCelPositions" | "propagateFrameToRange" | "deleteFrame" | "deleteTag" | "setOnionSkin" | "renderOnionSkin" | "compareFrames" | "setCelOpacity">;
export type PaletteTransformPort = Pick<AsepriteGateway, "getColorStats" | "getPalette" | "extractPalette" | "remapColorsInCelRange" | "listPalettePresets" | "applyPalettePreset" | "generateColorRamp" | "quantizeToPalette" | "setColorMode" | "getPixelColor" | "getPixelsRect" | "getCompositePixel" | "getCompositeRect" | "moveRegion" | "copyRegion" | "eraseRegion" | "eraseColor" | "flipLayer" | "rotateLayer" | "resizeCanvas" | "cropCanvas">;
export type TextTileSlicePort = Pick<AsepriteGateway, "listTextFonts" | "measureText" | "drawText" | "drawOnTile" | "setTiles" | "getTileAt" | "getTilemapInfo" | "createSlice" | "setSliceCenter" | "setSlicePivot" | "listSlices" | "deleteSlice">;
export type AnimationQualityPort = Pick<AsepriteGateway, "ensureLayersPresent" | "auditAnimation" | "animationSanitize" | "startPreviewServer" | "stopPreviewServer" | "copyLayersBetweenSprites" | "getSpriteInfo" | "duplicateFrameRange" | "propagateCels" | "tweenCelPositionsEased" | "oscillateCelPositions" | "tweenCelOpacityEased" | "tweenCelScaleEased" | "setLayer">;
export type WorkflowPort = Pick<AsepriteGateway, "animationWorkflowGuide" | "runLuaScript">;
export type EffectsPort = Pick<AsepriteGateway, "outlineNative" | "adjustHslNative" | "adjustBrightnessContrast" | "invertColors" | "outlineCel" | "replaceColor" | "adjustHsl" | "applyConvolution" | "listConvolutionMatrices" | "applyDitherGradient" | "applyDitherPattern" | "setTag">;
export type SceneExportPort = Pick<AsepriteGateway, "createTilemapLayer" | "validateScene" | "exportSpritesheet">;
