import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as z from "zod/v4";
import type { AssetOperationResult } from "../../domain/asset-operations.js";
import type { SpriteEffectsGateway } from "../../domain/sprite-effects.js";

const COLOR = /^#?(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/;

export class SpriteEffectsToolController {
  public constructor(private readonly effects: SpriteEffectsGateway) {}
  public register(server: McpServer): void {
    server.registerTool("apply_pixel_outline", { description: "Add a deterministic pixel outline around opaque sprite edges.", inputSchema: { input_filename: z.string().min(1), output_filename: z.string().min(1), color: z.string().regex(COLOR), thickness: z.number().int().min(1).max(8).default(1), format: z.enum(["png", "gif"]).optional() } }, async ({ input_filename, output_filename, color, thickness, format }) => this.result(await this.effects.applyPixelOutline({ inputFilename: input_filename, outputFilename: output_filename, color, thickness, ...(format ? { format } : {}) })));
    server.registerTool("apply_color_grade", { description: "Apply deterministic brightness, contrast, and saturation grading to a sprite.", inputSchema: { input_filename: z.string().min(1), output_filename: z.string().min(1), brightness: z.number().min(-1).max(1).default(0), contrast: z.number().min(0).max(2).default(1), saturation: z.number().min(0).max(2).default(1), format: z.enum(["png", "gif"]).optional() } }, async ({ input_filename, output_filename, brightness, contrast, saturation, format }) => this.result(await this.effects.applyColorGrade({ inputFilename: input_filename, outputFilename: output_filename, brightness, contrast, saturation, ...(format ? { format } : {}) })));
    server.registerTool("generate_sprite_shadow", { description: "Generate a deterministic clipped sprite shadow from alpha data.", inputSchema: { input_filename: z.string().min(1), output_filename: z.string().min(1), offset_x: z.number().int().min(-32).max(32), offset_y: z.number().int().min(-32).max(32), color: z.string().regex(COLOR), opacity: z.number().min(0).max(1).default(0.45), format: z.enum(["png", "gif"]).optional() } }, async ({ input_filename, output_filename, offset_x, offset_y, color, opacity, format }) => this.result(await this.effects.generateSpriteShadow({ inputFilename: input_filename, outputFilename: output_filename, offsetX: offset_x, offsetY: offset_y, color, opacity, ...(format ? { format } : {}) })));
    server.registerTool("generate_particle_burst", { description: "Generate a deterministic animated particle burst GIF for impact, healing, magic, or dust.", inputSchema: { output_filename: z.string().min(1), width: z.number().int().min(8).max(512), height: z.number().int().min(8).max(512), frames: z.number().int().min(2).max(24), particle_count: z.number().int().min(1).max(128), seed: z.number().int(), color: z.string().regex(COLOR), delay_ms: z.number().int().positive().default(80) } }, async ({ output_filename, width, height, frames, particle_count, seed, color, delay_ms }) => this.result(await this.effects.generateParticleBurst({ outputFilename: output_filename, width, height, frames, particleCount: particle_count, seed, color, delayMs: delay_ms })));
    server.registerTool("generate_normal_map", { description: "Generate a deterministic tangent-space normal map from sprite alpha depth.", inputSchema: { input_filename: z.string().min(1), output_filename: z.string().min(1), strength: z.number().min(0).max(8).default(2), format: z.enum(["png", "gif"]).optional() } }, async ({ input_filename, output_filename, strength, format }) => this.result(await this.effects.generateNormalMap({ inputFilename: input_filename, outputFilename: output_filename, strength, ...(format ? { format } : {}) })));
  }
  private result(operation: AssetOperationResult): { isError?: boolean; content: [{ type: "text"; text: string }] } { return { isError: !operation.ok, content: [{ type: "text", text: operation.message }] }; }
}
