import type { IncomingMessage, ServerResponse } from "node:http";
import * as z from "zod/v4";
import type { AssetRecipeCreateInput } from "../../domain/asset-recipe.js";
import type { AssetRestUseCases } from "../../application/ports/AssetRestPorts.js";

const color = z.string().regex(/^#?(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/);
const qualityBatchSchema = z.object({ filenames: z.array(z.string().min(1)).min(1).max(32), max_colors: z.number().int().min(1).max(256).default(256), max_isolated_pixels: z.number().int().nonnegative().default(9007199254740991) });
const animationQualitySchema = z.object({ filename: z.string().min(1) });
const spriteNormalizationSchema = z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), manifest_filename: z.string().min(1), padding: z.number().int().min(0).max(16).default(0), pivot: z.enum(["center", "bottom_center"]).default("bottom_center"), format: z.enum(["png", "gif"]).optional() });
const animationSheetSchema = z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), manifest_filename: z.string().min(1), columns: z.number().int().min(1).max(16).optional(), padding: z.number().int().min(0).max(64).default(0) });
const spriteGeometrySchema = z.object({ filename: z.string().min(1), min_component_pixels: z.number().int().min(1).max(4096).default(1) });
const spriteHitboxSchema = z.object({ filename: z.string().min(1), output_filename: z.string().min(1), mode: z.enum(["components", "union"]).default("components"), padding: z.number().int().min(0).max(16).default(0), min_component_pixels: z.number().int().min(1).max(4096).default(1) });
const spriteRuntimeBundleSchema = z.object({ input_filename: z.string().min(1), sheet_filename: z.string().min(1), sheet_manifest_filename: z.string().min(1), hitbox_manifest_filename: z.string().min(1), bundle_manifest_filename: z.string().min(1), columns: z.number().int().min(1).max(16).optional(), sheet_padding: z.number().int().min(0).max(64).default(0), hitbox_mode: z.enum(["components", "union"]).default("components"), hitbox_padding: z.number().int().min(0).max(16).default(0), min_component_pixels: z.number().int().min(1).max(4096).default(1) });
const spriteAnchorsSchema = z.object({ filename: z.string().min(1), output_filename: z.string().min(1), min_component_pixels: z.number().int().min(1).max(4096).default(1) });
const recipeSchema = z.object({ asset_id: z.string().min(1), input_filename: z.string().min(1), output_prefix: z.string().min(1), format: z.enum(["png", "gif"]).default("png"), steps: z.array(z.enum(["outline", "color_grade", "material_texture", "depth_lighting", "shadow", "particles", "normal_map", "quality_gate"])).min(1).max(8), seed: z.number().int().default(1), material: z.enum(["water", "earth", "grass", "stone", "snow"]).default("earth"), direction: z.enum(["north", "south", "east", "west", "north_east", "north_west", "south_east", "south_west"]).default("south_east") });
const materialSchema = z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), material: z.enum(["water", "earth", "grass", "stone", "snow"]), seed: z.number().int(), intensity: z.number().min(0).max(1).default(0.6), format: z.enum(["png", "gif"]).optional() });
const lightingSchema = z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), direction: z.enum(["north", "south", "east", "west", "north_east", "north_west", "south_east", "south_west"]), strength: z.number().min(0).max(1).default(0.7), ambient: z.number().min(0).max(1).default(0.35), format: z.enum(["png", "gif"]).optional() });
const MAX_BODY_BYTES = 1024 * 1024;
const rainSchema = z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), seed: z.number().int(), intensity: z.number().min(0).max(1).default(0.55), wind: z.number().min(-1).max(1).default(0), color, frames: z.number().int().min(1).max(24).optional(), delay_ms: z.number().int().positive().default(90), format: z.enum(["png", "gif"]).optional() });
const motionSchema = z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), motion: z.enum(["idle", "walk", "run", "jump", "attack"]), frames: z.number().int().min(2).max(24).default(8), seed: z.number().int().default(1), amplitude: z.number().min(0).max(8).default(2), delay_ms: z.number().int().positive().default(90), format: z.enum(["png", "gif"]).optional() });
const seamlessSchema = z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), seam_width: z.number().int().min(1).max(32).default(1), format: z.enum(["png", "gif"]).optional() });
const waterReflectionSchema = z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), waterline: z.number().int().min(1).max(2048), frames: z.number().int().min(2).max(24).default(8), seed: z.number().int().default(1), amplitude: z.number().min(0).max(8).default(1), opacity: z.number().min(0).max(1).default(0.6), delay_ms: z.number().int().positive().default(90), format: z.enum(["png", "gif"]).optional() });
const waterCausticsSchema = z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), frames: z.number().int().min(2).max(24).default(8), seed: z.number().int().default(1), intensity: z.number().min(0).max(1).default(0.7), scale: z.number().int().min(1).max(32).default(4), color, delay_ms: z.number().int().positive().default(90), format: z.enum(["png", "gif"]).optional() });
const dayNightSchema = z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), frames: z.number().int().min(4).max(24).default(8), seed: z.number().int().default(1), intensity: z.number().min(0.05).max(1).default(0.8), delay_ms: z.number().int().positive().default(90), format: z.enum(["png", "gif"]).optional() });
const variantPackSchema = z.object({ input_filename: z.string().min(1), output_prefix: z.string().min(1), variants: z.array(z.enum(["rain", "fire", "earthquake", "birds", "night", "day_night", "walk", "water_reflection", "water_caustics"])).min(1).max(9), frames: z.number().int().min(2).max(24).default(8), seed: z.number().int().default(1), delay_ms: z.number().int().positive().default(90) });
const presetGenerationSchema = z.object({ preset_id: z.string().min(1), output_prefix: z.string().min(1), width: z.number().int().positive().max(2048), height: z.number().int().positive().max(2048), seed: z.number().int(), tile_size: z.number().int().min(4).max(128).default(16), detail_level: z.enum(["low", "medium", "high"]).default("high") });
const sceneEffectStackSchema = z.object({ input_filename: z.string().min(1), output_prefix: z.string().min(1), effects: z.array(z.enum(["rain", "water_reflection", "water_caustics", "day_night", "material_texture", "depth_lighting", "particles"])).min(1).max(7), frames: z.number().int().min(2).max(24).default(8), seed: z.number().int().default(1), delay_ms: z.number().int().positive().default(90), material: z.enum(["water", "earth", "grass", "stone", "snow"]).default("earth"), direction: z.enum(["north", "south", "east", "west", "north_east", "north_west", "south_east", "south_west"]).default("south_east"), particle_count: z.number().int().min(1).max(128).optional(), particle_color: color.optional(), format: z.enum(["png", "gif"]).default("gif") });
const qualityBundleSchema = z.object({ filename: z.string().min(1), max_colors: z.number().int().min(1).max(256).default(256), max_isolated_pixels: z.number().int().nonnegative().default(9007199254740991) });
const upscaleSchema = z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), scale: z.number().int().min(2).max(16), format: z.enum(["png", "gif"]).optional() });
const paletteHarmonizeSchema = z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), accent_color: z.string().regex(/^#?(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/), strength: z.number().min(0).max(1).default(0.65), max_colors: z.number().int().min(2).max(64).default(16), format: z.enum(["png", "gif"]).optional() });
const contactSheetSchema = z.object({ input_filenames: z.array(z.string().min(1)).min(1).max(64), output_filename: z.string().min(1), manifest_filename: z.string().min(1), cell_width: z.number().int().min(8).max(512), cell_height: z.number().int().min(8).max(512), columns: z.number().int().min(1).max(16).optional(), padding: z.number().int().min(0).max(64).default(0) });
const sceneExtensionSchema = z.object({ input_map_filename: z.string().min(1), output_map_filename: z.string().min(1), preview_filename: z.string().min(1).optional(), top: z.number().int().min(0).max(512).default(0), right: z.number().int().min(0).max(512).default(0), bottom: z.number().int().min(0).max(512).default(0), left: z.number().int().min(0).max(512).default(0), seed: z.number().int().default(1) });
const biomeTransitionSchema = z.object({ input_map_filename: z.string().min(1), output_map_filename: z.string().min(1), preview_filename: z.string().min(1).optional(), transition_width: z.number().int().min(1).max(8).default(2), seed: z.number().int().default(1) });
const scenePlanSchema = z.object({ item_ids: z.array(z.string().min(1)).min(1).max(24) });
const sceneComposeSchema = z.object({ item_ids: z.array(z.string().min(1)).min(1).max(24), output_filename: z.string().min(1), manifest_filename: z.string().min(1), width: z.number().int().min(16).max(2048), height: z.number().int().min(16).max(2048), padding: z.number().int().min(0).max(64).default(0) });
const sceneAnimationComposeSchema = z.object({ item_ids: z.array(z.string().min(1)).min(1).max(24), output_filename: z.string().min(1), manifest_filename: z.string().min(1), width: z.number().int().min(16).max(2048), height: z.number().int().min(16).max(2048), padding: z.number().int().min(0).max(64).default(0), frames: z.number().int().min(2).max(24).default(8), delay_ms: z.number().int().min(1).max(2000).default(90) });
const libraryVariantPackSchema = z.object({ item_ids: z.array(z.string().min(1)).min(1).max(24), output_prefix: z.string().min(1), variants: z.array(z.enum(["rain", "fire", "earthquake", "birds", "night", "day_night", "walk", "water_reflection", "water_caustics"])).min(1).max(9), frames: z.number().int().min(2).max(24).default(8), seed: z.number().int().default(1), delay_ms: z.number().int().min(1).max(2000).default(90) });
const manifestAuditSchema = z.object({ manifest_filename: z.string().min(1) });
const sceneRecommendationSchema = z.object({ prompt: z.string().optional(), category: z.string().optional(), required_kinds: z.array(z.enum(["sprite", "tileset", "scene", "effect", "character", "prop"])).max(6).optional(), required_tags: z.array(z.string().min(1)).max(12).optional(), required_variants: z.array(z.string().min(1)).max(9).optional(), limit: z.number().int().min(1).max(24).default(8), seed: z.number().int().default(1) });

export class AssetRestController {
  public constructor(private readonly useCases: AssetRestUseCases, private readonly version = "1.0.0") {}

  public async handle(request: IncomingMessage, response: ServerResponse): Promise<void> {
    const origin = request.headers.origin;
    try {
      const url = new URL(request.url ?? "/", "http://" + (request.headers.host ?? "127.0.0.1"));
      if (request.method === "OPTIONS") return this.send(response, 204, {}, origin);
      if (request.method === "GET" && url.pathname === "/api/v1/health") return this.send(response, 200, { data: { ok: true, service: "aseprite-asset-mcp-rest", version: this.version, architecture: "hexagonal" } }, origin);
      if (request.method === "GET" && url.pathname === "/api/v1/library/audit") { const audit = await this.useCases.assetLibraryAudit.audit(); return this.operation(response, audit, origin); }
      if (request.method === "GET" && url.pathname === "/api/v1/library/summary") { const summary = await this.useCases.assetLibrarySummary.summarize(); return this.operation(response, summary, origin); }
      if (request.method === "POST" && url.pathname === "/api/v1/assets/manifest-audit") { const value = manifestAuditSchema.parse(await this.readBody(request)); return this.operation(response, await this.useCases.assetManifestAudit.audit({ manifestFilename: value.manifest_filename }), origin); }
      if (request.method === "POST" && url.pathname === "/api/v1/library/recommendations") { const value = sceneRecommendationSchema.parse(await this.readBody(request)); return this.operation(response, await this.useCases.assetSceneRecommendation.recommend({ ...(value.prompt === undefined ? {} : { prompt: value.prompt }), ...(value.category === undefined ? {} : { category: value.category }), ...(value.required_kinds === undefined ? {} : { requiredKinds: [...value.required_kinds] }), ...(value.required_tags === undefined ? {} : { requiredTags: [...value.required_tags] }), ...(value.required_variants === undefined ? {} : { requiredVariants: [...value.required_variants] }), limit: value.limit, seed: value.seed }), origin); }
      if (request.method === "GET" && url.pathname === "/api/v1/library") return this.send(response, 200, { data: await this.useCases.assetLibrary.search({ ...(url.searchParams.get("query") ? { query: url.searchParams.get("query")! } : {}), ...(url.searchParams.get("category") ? { category: url.searchParams.get("category")! } : {}), ...(url.searchParams.has("limit") ? { limit: Number(url.searchParams.get("limit")) } : {}) }) }, origin);
      if (request.method === "GET" && url.pathname.match(/^\/api\/v1\/library\/items\/[^/]+\/(preview|sprite)$/)) { const parts = url.pathname.split("/"); const kind = parts.at(-1) as "preview" | "sprite"; const id = decodeURIComponent(parts.at(-2) ?? ""); const binary = await this.useCases.assetLibrary.binary(id, kind); return binary ? this.sendBinary(response, 200, binary.data, binary.contentType, origin) : this.send(response, 404, { error: "Asset library item not found" }, origin); }
      if (request.method === "GET" && url.pathname.startsWith("/api/v1/library/items/")) { const item = await this.useCases.assetLibrary.get(decodeURIComponent(url.pathname.slice("/api/v1/library/items/".length))); return item ? this.send(response, 200, { data: item }, origin) : this.send(response, 404, { error: "Asset library item not found" }, origin); }
      if (request.method === "GET" && url.pathname.match(/^\/api\/v1\/library\/presets\/[^/]+\/compose$/)) { const parts = url.pathname.split("/"); const composition = await this.useCases.assetLibrary.composePreset(decodeURIComponent(parts.at(-2) ?? "")); return composition ? this.send(response, 200, { data: composition }, origin) : this.send(response, 404, { error: "Asset library preset not found" }, origin); }
      if (request.method === "GET" && url.pathname.startsWith("/api/v1/library/presets/")) { const preset = await this.useCases.assetLibrary.preset(decodeURIComponent(url.pathname.slice("/api/v1/library/presets/".length))); return preset ? this.send(response, 200, { data: preset }, origin) : this.send(response, 404, { error: "Asset library preset not found" }, origin); }
      if (request.method !== "POST") return this.send(response, 404, { error: "Ruta no encontrada" }, origin);
      const body = await this.readBody(request);
      if (url.pathname === "/api/v1/recipes/execute") { const execution = await this.useCases.executeRecipe(this.toRecipeInput(recipeSchema.parse(body))); return this.send(response, execution.ok ? 200 : 422, { data: execution, ...(execution.ok ? {} : { error: execution.error ?? "Recipe execution failed" }) }, origin); }
      if (url.pathname === "/api/v1/library/scene-plan") { const value = scenePlanSchema.parse(body); try { return this.operation(response, await this.useCases.assetScenePlanner.plan([...value.item_ids]), origin); } catch (error) { throw error; } }
      if (url.pathname === "/api/v1/library/scene-compose") { const value = sceneComposeSchema.parse(body); return this.operation(response, await this.useCases.assetSceneComposer.compose({ itemIds: [...value.item_ids], outputFilename: value.output_filename, manifestFilename: value.manifest_filename, width: value.width, height: value.height, padding: value.padding }), origin); }
      if (url.pathname === "/api/v1/library/scene-animation-compose") { const value = sceneAnimationComposeSchema.parse(body); return this.operation(response, await this.useCases.assetSceneAnimationComposer.compose({ itemIds: [...value.item_ids], outputFilename: value.output_filename, manifestFilename: value.manifest_filename, width: value.width, height: value.height, padding: value.padding, frames: value.frames, delayMs: value.delay_ms }), origin); }
      if (url.pathname === "/api/v1/library/variants/pack") { const value = libraryVariantPackSchema.parse(body); return this.operation(response, await this.useCases.assetLibraryVariantPack.generate({ itemIds: [...value.item_ids], outputPrefix: value.output_prefix, variants: [...value.variants], frames: value.frames, seed: value.seed, delayMs: value.delay_ms }), origin); }
      if (url.pathname === "/api/v1/recipes") return this.send(response, 200, { data: this.useCases.createRecipe(this.toRecipeInput(recipeSchema.parse(body))) }, origin);
      if (url.pathname === "/api/v1/material-texture") { const value = materialSchema.parse(body); return this.operation(response, await this.useCases.applyMaterialTexture({ inputFilename: value.input_filename, outputFilename: value.output_filename, material: value.material, seed: value.seed, intensity: value.intensity, ...(value.format ? { format: value.format } : {}) }), origin); }
      if (url.pathname === "/api/v1/depth-lighting") { const value = lightingSchema.parse(body); return this.operation(response, await this.useCases.applyDepthLighting({ inputFilename: value.input_filename, outputFilename: value.output_filename, direction: value.direction, strength: value.strength, ambient: value.ambient, ...(value.format ? { format: value.format } : {}) }), origin); }
      if (url.pathname === "/api/v1/effects/outline") return this.operation(response, await this.useCases.spriteEffects.applyPixelOutline(this.parseOutline(body)), origin);
      if (url.pathname === "/api/v1/effects/color-grade") return this.operation(response, await this.useCases.spriteEffects.applyColorGrade(this.parseColorGrade(body)), origin);
      if (url.pathname === "/api/v1/effects/shadow") return this.operation(response, await this.useCases.spriteEffects.generateSpriteShadow(this.parseShadow(body)), origin);
      if (url.pathname === "/api/v1/effects/particles") return this.operation(response, await this.useCases.spriteEffects.generateParticleBurst(this.parseParticles(body)), origin);
      if (url.pathname === "/api/v1/effects/normal-map") return this.operation(response, await this.useCases.spriteEffects.generateNormalMap(this.parseNormalMap(body)), origin);
      if (url.pathname === "/api/v1/effects/rain") { const value = rainSchema.parse(body); return this.operation(response, await this.useCases.spriteEffects.generateRainOverlay({ inputFilename: value.input_filename, outputFilename: value.output_filename, seed: value.seed, intensity: value.intensity, wind: value.wind, color: value.color, ...(value.frames === undefined ? {} : { frames: value.frames }), delayMs: value.delay_ms, ...(value.format ? { format: value.format } : {}) }), origin); }
      if (url.pathname === "/api/v1/effects/motion") { const value = motionSchema.parse(body); return this.operation(response, await this.useCases.spriteEffects.generateMotionPack({ inputFilename: value.input_filename, outputFilename: value.output_filename, motion: value.motion, frames: value.frames, seed: value.seed, amplitude: value.amplitude, delayMs: value.delay_ms, ...(value.format ? { format: value.format } : {}) }), origin); }
      if (url.pathname === "/api/v1/effects/seamless") { const value = seamlessSchema.parse(body); return this.operation(response, await this.useCases.spriteEffects.generateSeamlessTexture({ inputFilename: value.input_filename, outputFilename: value.output_filename, seamWidth: value.seam_width, ...(value.format ? { format: value.format } : {}) }), origin); }
      if (url.pathname === "/api/v1/effects/water-reflection") { const value = waterReflectionSchema.parse(body); return this.operation(response, await this.useCases.spriteEffects.generateWaterReflection({ inputFilename: value.input_filename, outputFilename: value.output_filename, waterline: value.waterline, frames: value.frames, seed: value.seed, amplitude: value.amplitude, opacity: value.opacity, delayMs: value.delay_ms, ...(value.format ? { format: value.format } : {}) }), origin); }
      if (url.pathname === "/api/v1/effects/water-caustics") { const value = waterCausticsSchema.parse(body); return this.operation(response, await this.useCases.spriteEffects.generateWaterCaustics({ inputFilename: value.input_filename, outputFilename: value.output_filename, frames: value.frames, seed: value.seed, intensity: value.intensity, scale: value.scale, color: value.color, delayMs: value.delay_ms, ...(value.format ? { format: value.format } : {}) }), origin); }
      if (url.pathname === "/api/v1/effects/day-night") { const value = dayNightSchema.parse(body); return this.operation(response, await this.useCases.spriteEffects.generateDayNightCycle({ inputFilename: value.input_filename, outputFilename: value.output_filename, frames: value.frames, seed: value.seed, intensity: value.intensity, delayMs: value.delay_ms, ...(value.format ? { format: value.format } : {}) }), origin); }
      if (url.pathname === "/api/v1/variants/pack") { const value = variantPackSchema.parse(body); return this.operation(response, await this.useCases.variantPack.generateVariantPack({ inputFilename: value.input_filename, outputPrefix: value.output_prefix, variants: [...value.variants], frames: value.frames, seed: value.seed, delayMs: value.delay_ms }), origin); }
      if (url.pathname === "/api/v1/library/presets/generate") { const value = presetGenerationSchema.parse(body); return this.operation(response, await this.useCases.presetGeneration.generate({ presetId: value.preset_id, outputPrefix: value.output_prefix, width: value.width, height: value.height, seed: value.seed, tileSize: value.tile_size, detailLevel: value.detail_level }), origin); }
      if (url.pathname === "/api/v1/effects/scene-stack") { const value = sceneEffectStackSchema.parse(body); return this.operation(response, await this.useCases.sceneEffectStack.generateSceneEffectStack({ inputFilename: value.input_filename, outputPrefix: value.output_prefix, effects: [...value.effects], frames: value.frames, seed: value.seed, delayMs: value.delay_ms, material: value.material, direction: value.direction, ...(value.particle_count === undefined ? {} : { particleCount: value.particle_count }), ...(value.particle_color === undefined ? {} : { particleColor: value.particle_color }), format: value.format }), origin); }
      if (url.pathname === "/api/v1/assets/quality-bundle") { const value = qualityBundleSchema.parse(body); return this.operation(response, await this.useCases.imageAssets.qualityBundle({ filename: value.filename, maxColors: value.max_colors, maxIsolatedPixels: value.max_isolated_pixels }), origin); }
      if (url.pathname === "/api/v1/assets/quality-batch") { const value = qualityBatchSchema.parse(body); return this.operation(response, await this.useCases.batchQuality.inspect({ filenames: [...value.filenames], maxColors: value.max_colors, maxIsolatedPixels: value.max_isolated_pixels }), origin); }
      if (url.pathname === "/api/v1/assets/animation-quality") { const value = animationQualitySchema.parse(body); return this.operation(response, await this.useCases.animationQuality.inspect({ filename: value.filename }), origin); }
      if (url.pathname === "/api/v1/assets/normalize-sprite") { const value = spriteNormalizationSchema.parse(body); return this.operation(response, await this.useCases.spriteNormalization.normalize({ inputFilename: value.input_filename, outputFilename: value.output_filename, manifestFilename: value.manifest_filename, padding: value.padding, pivot: value.pivot, ...(value.format ? { format: value.format } : {}) }), origin); }
      if (url.pathname === "/api/v1/assets/animation-sheet") { const value = animationSheetSchema.parse(body); return this.operation(response, await this.useCases.animationSheet.build({ inputFilename: value.input_filename, outputFilename: value.output_filename, manifestFilename: value.manifest_filename, ...(value.columns === undefined ? {} : { columns: value.columns }), padding: value.padding }), origin); }
      if (url.pathname === "/api/v1/assets/sprite-geometry") { const value = spriteGeometrySchema.parse(body); return this.operation(response, await this.useCases.spriteGeometry.inspect({ filename: value.filename, minComponentPixels: value.min_component_pixels }), origin); }
      if (url.pathname === "/api/v1/assets/sprite-hitboxes") { const value = spriteHitboxSchema.parse(body); return this.operation(response, await this.useCases.spriteHitbox.generate({ filename: value.filename, outputFilename: value.output_filename, mode: value.mode, padding: value.padding, minComponentPixels: value.min_component_pixels }), origin); }
      if (url.pathname === "/api/v1/assets/sprite-runtime-bundle") { const value = spriteRuntimeBundleSchema.parse(body); return this.operation(response, await this.useCases.spriteRuntimeBundle.build({ inputFilename: value.input_filename, sheetFilename: value.sheet_filename, sheetManifestFilename: value.sheet_manifest_filename, hitboxManifestFilename: value.hitbox_manifest_filename, bundleManifestFilename: value.bundle_manifest_filename, ...(value.columns === undefined ? {} : { columns: value.columns }), sheetPadding: value.sheet_padding, hitboxMode: value.hitbox_mode, hitboxPadding: value.hitbox_padding, minComponentPixels: value.min_component_pixels }), origin); }
      if (url.pathname === "/api/v1/assets/sprite-anchors") { const value = spriteAnchorsSchema.parse(body); return this.operation(response, await this.useCases.spriteAnchors.generate({ filename: value.filename, outputFilename: value.output_filename, minComponentPixels: value.min_component_pixels }), origin); }
      if (url.pathname === "/api/v1/effects/upscale") { const value = upscaleSchema.parse(body); return this.operation(response, await this.useCases.imageAssets.upscalePixelArt({ inputFilename: value.input_filename, outputFilename: value.output_filename, scale: value.scale, ...(value.format ? { format: value.format } : {}) }), origin); }
      if (url.pathname === "/api/v1/assets/palette-harmonize") { const value = paletteHarmonizeSchema.parse(body); return this.operation(response, await this.useCases.imageAssets.harmonizePalette({ inputFilename: value.input_filename, outputFilename: value.output_filename, accentColor: value.accent_color, strength: value.strength, maxColors: value.max_colors, ...(value.format ? { format: value.format } : {}) }), origin); }
      if (url.pathname === "/api/v1/assets/contact-sheet") { const value = contactSheetSchema.parse(body); return this.operation(response, await this.useCases.contactSheet.build({ inputFilenames: [...value.input_filenames], outputFilename: value.output_filename, manifestFilename: value.manifest_filename, cellWidth: value.cell_width, cellHeight: value.cell_height, ...(value.columns === undefined ? {} : { columns: value.columns }), padding: value.padding }), origin); }
      if (url.pathname === "/api/v1/scenes/extend") { const value = sceneExtensionSchema.parse(body); return this.operation(response, await this.useCases.visualAssets.extendScene({ inputMapFilename: value.input_map_filename, outputMapFilename: value.output_map_filename, ...(value.preview_filename ? { previewFilename: value.preview_filename } : {}), padding: { top: value.top, right: value.right, bottom: value.bottom, left: value.left }, seed: value.seed }), origin); }
      if (url.pathname === "/api/v1/scenes/biome-transition") { const value = biomeTransitionSchema.parse(body); return this.operation(response, await this.useCases.visualAssets.generateBiomeTransition({ inputMapFilename: value.input_map_filename, outputMapFilename: value.output_map_filename, ...(value.preview_filename ? { previewFilename: value.preview_filename } : {}), transitionWidth: value.transition_width, seed: value.seed }), origin); }
      return this.send(response, 404, { error: "Ruta no encontrada" }, origin);
    } catch (error) { const message = error instanceof Error ? error.message : String(error); return this.send(response, message.startsWith("Request body exceeds") ? 413 : 400, { error: message }, origin); }
  }

  private toRecipeInput(value: z.infer<typeof recipeSchema>): AssetRecipeCreateInput { return { assetId: value.asset_id, inputFilename: value.input_filename, outputPrefix: value.output_prefix, format: value.format, steps: value.steps, seed: value.seed, material: value.material, direction: value.direction }; }
  private parseOutline(body: unknown) { return z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), color, thickness: z.number().int().min(1).max(8).default(1), format: z.enum(["png", "gif"]).optional() }).transform((value) => ({ inputFilename: value.input_filename, outputFilename: value.output_filename, color: value.color, thickness: value.thickness, ...(value.format ? { format: value.format } : {}) })).parse(body); }
  private parseColorGrade(body: unknown) { return z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), brightness: z.number().min(-1).max(1).default(0), contrast: z.number().min(0).max(2).default(1), saturation: z.number().min(0).max(2).default(1), format: z.enum(["png", "gif"]).optional() }).transform((value) => ({ inputFilename: value.input_filename, outputFilename: value.output_filename, brightness: value.brightness, contrast: value.contrast, saturation: value.saturation, ...(value.format ? { format: value.format } : {}) })).parse(body); }
  private parseShadow(body: unknown) { return z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), offset_x: z.number().int().min(-32).max(32), offset_y: z.number().int().min(-32).max(32), color, opacity: z.number().min(0).max(1).default(0.45), format: z.enum(["png", "gif"]).optional() }).transform((value) => ({ inputFilename: value.input_filename, outputFilename: value.output_filename, offsetX: value.offset_x, offsetY: value.offset_y, color: value.color, opacity: value.opacity, ...(value.format ? { format: value.format } : {}) })).parse(body); }
  private parseParticles(body: unknown) { return z.object({ output_filename: z.string().min(1), width: z.number().int().min(8).max(512), height: z.number().int().min(8).max(512), frames: z.number().int().min(2).max(24), particle_count: z.number().int().min(1).max(128), seed: z.number().int(), color, delay_ms: z.number().int().positive().default(80) }).transform((value) => ({ outputFilename: value.output_filename, width: value.width, height: value.height, frames: value.frames, particleCount: value.particle_count, seed: value.seed, color: value.color, delayMs: value.delay_ms })).parse(body); }
  private parseNormalMap(body: unknown) { return z.object({ input_filename: z.string().min(1), output_filename: z.string().min(1), strength: z.number().min(0).max(8).default(2), format: z.enum(["png", "gif"]).optional() }).transform((value) => ({ inputFilename: value.input_filename, outputFilename: value.output_filename, strength: value.strength, ...(value.format ? { format: value.format } : {}) })).parse(body); }
  private async readBody(request: IncomingMessage): Promise<unknown> {
    let raw = "";
    let size = 0;
    for await (const chunk of request) { const piece = chunk.toString(); size += Buffer.byteLength(piece); if (size > MAX_BODY_BYTES) throw new Error("Request body exceeds 1 MiB limit"); raw += piece; }
    return raw ? JSON.parse(raw) : {};
  }
  private operation(response: ServerResponse, result: { ok: boolean; message: string }, origin?: string): void { let data: unknown; try { data = JSON.parse(result.message); } catch { data = { message: result.message }; } this.send(response, result.ok ? 200 : 422, { data, ...(result.ok ? {} : { error: result.message }) }, origin); }
  private send(response: ServerResponse, status: number, data: unknown, origin?: string): void { const allowedOrigin = this.localOrigin(origin); response.writeHead(status, { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": allowedOrigin, "access-control-allow-headers": "content-type", "access-control-allow-methods": "GET,POST,OPTIONS", vary: "origin" }); response.end(JSON.stringify(data)); }
  private sendBinary(response: ServerResponse, status: number, data: Uint8Array, contentType: string, origin?: string): void { const allowedOrigin = this.localOrigin(origin); response.writeHead(status, { "content-type": contentType, "content-length": String(data.byteLength), "cache-control": "no-store", "access-control-allow-origin": allowedOrigin, "access-control-allow-headers": "content-type", "access-control-allow-methods": "GET,POST,OPTIONS", vary: "origin" }); response.end(Buffer.from(data)); }
  private localOrigin(origin?: string): string { if (!origin) return "null"; try { const parsed = new URL(origin); return parsed.protocol === "http:" && (parsed.hostname === "localhost" || parsed.hostname === "127.0.0.1") ? origin : "null"; } catch { return "null"; } }
}
