import type { ToolCatalogList, ToolDescriptor, ToolFolderSummary } from "../../domain/tool-catalog.js";

// Explicit folder assignment for every tool exposed by the MCP server.
// No heuristics and no silent fallback: a tool without an entry fails fast in tests.
// `asset/core` is reserved for framework-level document tools that do not belong to a
// narrower feature folder.
const TOOL_FOLDERS: Record<string, string> = {
  add_frame: "asset/animation",
  add_frames: "asset/animation",
  add_group: "asset/layers",
  add_layer: "asset/layers",
  adjust_brightness_contrast: "asset/effects",
  adjust_hsl: "asset/effects",
  adjust_hsl_native: "asset/effects",
  animation_sanitize: "asset/animation",
  animation_workflow_guide: "asset/animation",
  apply_color_grade: "asset/effects",
  apply_convolution: "asset/effects",
  apply_depth_lighting: "asset/lighting",
  apply_dither_gradient: "asset/drawing",
  apply_dither_pattern: "asset/effects",
  apply_enhancement_batch: "asset/recipes",
  apply_enhancement_plan: "asset/recipes",
  apply_gradient_rect: "asset/drawing",
  apply_material_texture: "asset/material",
  apply_palette_preset: "asset/palette",
  apply_pixel_outline: "asset/effects",
  audit_animation: "asset/animation",
  audit_asset_library: "meta/asset-library",
  audit_asset_manifest: "meta/assets",
  batch_asset_job: "asset/recipes",
  build_animation_sheet: "asset/animation",
  build_contact_sheet: "asset/preview",
  build_scene_bundle: "library/scenes",
  build_sprite_runtime_bundle: "asset/runtime",
  build_terrain_tileset: "asset/tilemap",
  cancel_asset_job: "asset/jobs",
  clear_cel: "asset/animation",
  compare_frames: "asset/animation",
  compose_asset_preset: "meta/asset-library",
  compose_asset_scene: "scene/composition",
  compose_asset_scene_animation: "scene/composition",
  convert_animation_to_pixel_art: "asset/import",
  convert_image_to_pixel_art: "asset/import",
  copy_cel: "asset/animation",
  copy_frame: "asset/animation",
  copy_layers_between_sprites: "asset/layers",
  copy_region: "asset/selection",
  copy_sprite: "asset/export",
  create_asset_recipe: "asset/recipes",
  create_canvas: "asset/core",
  create_cel: "asset/animation",
  create_character_plan: "asset/recipes",
  create_scene_plan: "asset/recipes",
  create_slice: "asset/slices",
  create_style_bible: "asset/style",
  create_tilemap_layer: "asset/tilemap",
  crop_canvas: "asset/transform",
  delete_frame: "asset/animation",
  delete_layer: "asset/layers",
  delete_slice: "asset/slices",
  delete_tag: "asset/animation",
  draw_circle: "asset/drawing",
  draw_circle_at: "asset/drawing",
  draw_ellipse_at: "asset/drawing",
  draw_line: "asset/drawing",
  draw_line_at: "asset/drawing",
  draw_on_tile: "asset/tilemap",
  draw_path: "asset/drawing",
  draw_pixels: "asset/drawing",
  draw_pixels_at: "asset/drawing",
  draw_polygon: "asset/drawing",
  draw_rectangle: "asset/drawing",
  draw_rectangle_at: "asset/drawing",
  draw_text: "asset/text",
  duplicate_frame_range: "asset/animation",
  duplicate_layer: "asset/layers",
  ensure_layers_present: "asset/layers",
  erase_color: "asset/palette",
  erase_region: "asset/selection",
  execute_asset_recipe: "asset/recipes",
  export_animation_gif: "asset/export",
  export_asset_pack: "asset/export",
  export_frame: "asset/export",
  export_layers: "asset/export",
  export_sprite: "asset/export",
  export_spritesheet: "asset/export",
  export_tag: "asset/export",
  extend_scene: "asset/world",
  extract_palette: "asset/palette",
  fill_area: "asset/drawing",
  fill_area_at: "asset/drawing",
  flatten_sprite: "asset/layers",
  flip_layer: "asset/layers",
  generate_asset_preset: "meta/asset-library",
  generate_beach_scene: "asset/world",
  generate_biome_transition: "asset/world",
  generate_color_ramp: "asset/palette",
  generate_day_night_cycle: "asset/effects",
  generate_environment_pack: "asset/world",
  generate_library_variant_pack: "library/variants",
  generate_motion_pack: "asset/effects",
  generate_normal_map: "asset/effects",
  generate_particle_burst: "asset/particles",
  generate_rain_overlay: "asset/effects",
  generate_scene_effect_stack: "asset/effects",
  generate_seamless_texture: "asset/effects",
  generate_source_variant_pack: "asset/effects",
  generate_sprite_anchors: "asset/runtime",
  generate_sprite_hitboxes: "asset/runtime",
  generate_sprite_shadow: "asset/effects",
  generate_water_caustics: "asset/effects",
  generate_water_reflection: "asset/effects",
  generate_world_map: "asset/world",
  get_asset_job_status: "asset/jobs",
  get_asset_library: "meta/asset-library",
  get_asset_library_item: "meta/asset-library",
  get_asset_preset: "meta/asset-library",
  get_color_stats: "asset/palette",
  get_composite_pixel: "asset/drawing",
  get_composite_rect: "asset/drawing",
  get_palette: "asset/palette",
  get_pixel_color: "asset/palette",
  get_pixels_rect: "asset/drawing",
  get_sprite_info: "asset/layers",
  get_tile_at: "asset/tilemap",
  get_tilemap_info: "asset/tilemap",
  get_tools_by_folder: "meta/catalog",
  get_tools_list: "meta/catalog",
  get_tools_search: "meta/catalog",
  harmonize_asset_palette: "asset/palette",
  import_image_as_layer: "asset/import",
  inspect_animation_quality: "asset/animation",
  inspect_asset_batch: "asset/quality",
  inspect_asset_bundle: "asset/quality",
  inspect_reference: "asset/quality",
  inspect_sprite_geometry: "asset/quality",
  invert_colors: "asset/effects",
  list_convolution_matrices: "asset/effects",
  list_palette_presets: "asset/palette",
  list_slices: "asset/slices",
  list_text_fonts: "asset/text",
  measure_text: "asset/text",
  merge_layer_down: "asset/layers",
  move_region: "asset/selection",
  normalize_sprite: "asset/runtime",
  offset_cel_positions: "asset/animation",
  oscillate_cel_positions: "asset/animation",
  outline_native: "asset/effects",
  plan_asset_scene: "scene/composition",
  propagate_cels: "asset/animation",
  propagate_frame_to_range: "asset/animation",
  quantize_to_palette: "asset/palette",
  recommend_asset_scene: "library/recommendations",
  remap_colors_in_cel_range: "asset/palette",
  rename_layer: "asset/layers",
  render_onion_skin: "asset/animation",
  reorder_layer: "asset/layers",
  replace_color: "asset/palette",
  resize_canvas: "asset/transform",
  rotate_layer: "asset/layers",
  run_asset_quality_gate: "asset/quality",
  run_asset_recipe: "asset/recipes",
  run_lua_script: "developer/script",
  server_capabilities: "meta/catalog",
  set_cel_opacity: "asset/animation",
  set_cel_position: "asset/animation",
  set_color_mode: "asset/palette",
  set_frame: "asset/animation",
  set_frame_duration: "asset/animation",
  set_frame_duration_all: "asset/animation",
  set_layer: "asset/layers",
  set_layer_blend_mode: "asset/layers",
  set_layer_opacity: "asset/layers",
  set_layer_visibility: "asset/layers",
  set_onion_skin: "asset/animation",
  set_palette: "asset/palette",
  set_slice_center: "asset/slices",
  set_slice_pivot: "asset/slices",
  set_tag: "asset/animation",
  set_tiles: "asset/tilemap",
  start_asset_job: "asset/jobs",
  start_preview_server: "asset/preview",
  stop_preview_server: "asset/preview",
  suggest_enhancement_plan: "asset/recipes",
  summarize_asset_library: "meta/asset-library",
  tween_cel_opacity_eased: "asset/animation",
  tween_cel_positions: "asset/animation",
  tween_cel_positions_eased: "asset/animation",
  tween_cel_scale_eased: "asset/animation",
  upscale_pixel_art: "asset/drawing",
  validate_scene: "asset/quality",
};

// One real, agent-oriented line per tool: what it does and its key distinction.
const TOOL_DESCRIPTIONS: Record<string, string> = {
  add_frame: "Add one animation frame.",
  add_frames: "Add a deterministic number of animation frames.",
  add_group: "Add a named layer group to an Aseprite document.",
  add_layer: "Add a named layer, optionally inside a group.",
  adjust_brightness_contrast: "Apply Aseprite native brightness and contrast to a layer/frame, optionally bounded to a region.",
  adjust_hsl: "Shift hue, saturation, and lightness on an opaque cel while preserving alpha.",
  adjust_hsl_native: "Apply Aseprite native hue, saturation, and lightness adjustment.",
  animation_sanitize: "Normalize animation cels and optionally repair out-of-range activity.",
  animation_workflow_guide: "Return a concise deterministic guide for character, environment, or general animation workflows.",
  apply_color_grade: "Apply deterministic raster brightness, contrast, and saturation grading to a PNG or GIF.",
  apply_convolution: "Apply a built-in Aseprite convolution matrix to a layer and frame.",
  apply_depth_lighting: "Add deterministic depth-aware directional lighting to a sprite while preserving transparency and source data.",
  apply_dither_gradient: "Fill a rectangle with a two-color Bayer-dithered gradient.",
  apply_dither_pattern: "Fill a rectangle with a uniform Bayer-dithered mix of two colors.",
  apply_enhancement_batch: "Enhance up to 24 assets in one deterministic batch, isolating per-file failures and preserving every source.",
  apply_enhancement_plan: "Inspect, plan, enhance, and quality-gate one asset to a new file in one deterministic non-destructive call.",
  apply_gradient_rect: "Apply a horizontal or vertical linear gradient to a rectangle on a named layer and animation frame.",
  apply_material_texture: "Add deterministic water, earth, grass, stone, or snow granularity while preserving transparency and source data.",
  apply_palette_preset: "Apply a built-in retro palette preset to the sprite.",
  apply_pixel_outline: "Add a deterministic multi-thickness pixel outline around opaque raster sprite edges.",
  audit_animation: "Audit animation cels, overlaps, and declared frame ranges.",
  audit_asset_library: "Audit library ids, preset references, categories, folders, and navigable asset paths before composing a scene.",
  audit_asset_manifest: "Audit files referenced by a generated manifest, including missing, empty, format, and SHA-256 metadata.",
  batch_asset_job: "Run several compact asset recipes in order or return one batch plan.",
  build_animation_sheet: "Assemble all frames of a PNG or GIF into a deterministic PNG spritesheet and write coordinates, bottom-center pivots, and delays to a manifest.",
  build_contact_sheet: "Fit heterogeneous sprite previews into a deterministic nearest-neighbor contact sheet and write a navigable JSON manifest.",
  build_scene_bundle: "Build a static PNG scene, animated GIF scene, and both navigation manifests through one deterministic operation.",
  build_sprite_runtime_bundle: "Build one deterministic runtime bundle with an animation sheet, timing manifest, and sprite hitbox manifest.",
  build_terrain_tileset: "Build a terrain tileset with adjacency variants and a manifest for tilemap assembly.",
  cancel_asset_job: "Request cancellation of a queued or running asynchronous asset job.",
  clear_cel: "Delete a cel from a named layer and frame.",
  compare_frames: "Compare two flattened animation frames and return changed-pixel metrics as JSON.",
  compose_asset_preset: "Compose one scene preset into compact assets and ordered layers for a single low-token request.",
  compose_asset_scene: "Compose selected library previews into a deterministic PNG and navigable manifest.",
  compose_asset_scene_animation: "Compose selected animated library previews into a deterministic GIF and frame manifest.",
  convert_animation_to_pixel_art: "Convert all image frames to pixel art and preserve animation delays.",
  convert_image_to_pixel_art: "Convert one image to pixel art with a deterministic shared palette.",
  copy_cel: "Copy one layer cel to another frame, replacing the destination by default.",
  copy_frame: "Copy all cels from one frame to another frame or append a new frame.",
  copy_layers_between_sprites: "Copy selected animation layers and cels from one Aseprite document into another.",
  copy_region: "Copy a rectangular region to a layer and frame destination.",
  copy_sprite: "Copy a sprite to another Aseprite document, refusing to overwrite by default.",
  create_asset_recipe: "Compose a deterministic, reviewable multi-effect asset recipe without executing it.",
  create_canvas: "Create a new Aseprite canvas.",
  create_cel: "Create an empty cel at a layer and frame when one does not already exist.",
  create_character_plan: "Create a deterministic, auditable TypeScript plan for a layered character and its Godot exports.",
  create_scene_plan: "Create a deterministic, auditable TypeScript plan for a tilemap scene and its Godot exports.",
  create_slice: "Create a named rectangular slice.",
  create_style_bible: "Create a deterministic visual style contract for sprites and maps.",
  create_tilemap_layer: "Create a tilemap layer and set the Aseprite grid.",
  crop_canvas: "Crop the sprite canvas to a rectangle.",
  delete_frame: "Delete one animation frame while keeping at least one frame in the sprite.",
  delete_layer: "Delete a named layer from an Aseprite document.",
  delete_slice: "Delete a named slice.",
  delete_tag: "Delete an existing animation tag.",
  draw_circle: "Draw an ellipse-bounded circle.",
  draw_circle_at: "Draw an ellipse-bounded circle on a named layer and animation frame.",
  draw_ellipse_at: "Draw a filled or outlined ellipse on a named layer and animation frame.",
  draw_line: "Draw a Bresenham line with optional pixel thickness.",
  draw_line_at: "Draw a Bresenham line on a named layer and animation frame.",
  draw_on_tile: "Draw pixels onto a tilemap tileset tile.",
  draw_path: "Draw a polyline on a named layer and animation frame.",
  draw_pixels: "Draw explicit pixels on the active cel.",
  draw_pixels_at: "Draw explicit pixels on a named layer and animation frame, creating the cel when requested.",
  draw_polygon: "Draw a filled or outlined polygon on a named layer and animation frame.",
  draw_rectangle: "Draw a filled or outlined pixel-art rectangle on the active Aseprite layer.",
  draw_rectangle_at: "Draw a filled or outlined rectangle on a named layer and animation frame.",
  draw_text: "Rasterize and draw text into a sprite layer and frame.",
  duplicate_frame_range: "Append one or more copies of an inclusive animation frame range.",
  duplicate_layer: "Duplicate a layer and its cels across all frames.",
  ensure_layers_present: "Ensure cels exist for named layers across a frame range.",
  erase_color: "Erase opaque pixels matching a color within channel tolerance.",
  erase_region: "Erase a rectangular region to transparency.",
  execute_asset_recipe: "Execute a composed multi-effect asset recipe through the shared visual services, step by step.",
  export_animation_gif: "Convert a PNG, GIF, or animated image into a GIF while preserving frames.",
  export_asset_pack: "Pack equal-size images into one atlas PNG and write a JSON manifest with every cell position.",
  export_frame: "Export one animation frame as a PNG with nearest-neighbor integer scaling.",
  export_layers: "Export each layer as a PNG and confirm that at least one new layer file was written.",
  export_sprite: "Export a sprite to a selected image format and confirm that Aseprite wrote an output file.",
  export_spritesheet: "Export a spritesheet and optional frame metadata for Godot.",
  export_tag: "Export an animation tag as an image or animation file after validating that the tag exists.",
  extend_scene: "Extend an existing deterministic scene around its borders while preserving the original layers and landmarks.",
  extract_palette: "Extract and persist an optimized palette with a bounded color count.",
  fill_area: "Fill a contiguous area from a seed pixel.",
  fill_area_at: "Fill a contiguous area on a named layer and animation frame.",
  flatten_sprite: "Flatten all layers into one layer.",
  flip_layer: "Flip a layer cel horizontally or vertically.",
  generate_asset_preset: "Execute a world preset: terrain, map, preview, waves, and a time-of-day transition in one response.",
  generate_beach_scene: "Generate a seeded beach map, preview, and animated wave GIF.",
  generate_biome_transition: "Generate transition metadata and a preview overlay between adjacent map biomes without mutating the source map.",
  generate_color_ramp: "Generate a hue-shifted dark-to-light pixel-art color ramp.",
  generate_day_night_cycle: "Generate deterministic day, sunset, night, and sunrise color-cycle frames while preserving transparency.",
  generate_environment_pack: "Generate a complete beach, forest, village, or cave asset pack.",
  generate_library_variant_pack: "Generate deterministic environmental variants for multiple asset library ids in one request.",
  generate_motion_pack: "Generate a deterministic idle, walk, run, jump, or attack cycle from a static or animated sprite.",
  generate_normal_map: "Generate a deterministic tangent-space normal map from sprite alpha depth.",
  generate_particle_burst: "Generate a deterministic animated particle burst GIF for impact, healing, magic, or dust.",
  generate_rain_overlay: "Generate a deterministic rain overlay while preserving the source dimensions and frame timing.",
  generate_scene_effect_stack: "Generate selected scene effects in one deterministic response while preserving the source.",
  generate_seamless_texture: "Make opposite texture borders match deterministically for repeatable water, earth, stone, or grass backgrounds.",
  generate_source_variant_pack: "Generate several deterministic environmental variants from one source asset in a single multi-output pack.",
  generate_sprite_anchors: "Generate deterministic placement anchors from sprite geometry for scene composition and game-engine transforms.",
  generate_sprite_hitboxes: "Generate a deterministic collision manifest from sprite geometry using component or union hitboxes with bounded padding.",
  generate_sprite_shadow: "Generate a deterministic clipped shadow from sprite alpha.",
  generate_water_caustics: "Generate deterministic animated light caustics for water surfaces and flooded interiors.",
  generate_water_reflection: "Generate deterministic animated reflections for oceans, beaches, and wave scenes.",
  generate_world_map: "Generate a seeded multi-biome map manifest and optional preview.",
  get_asset_job_status: "Read one asynchronous asset job without returning raw pixels.",
  get_asset_library: "Search the deterministic asset and preset library with compact results for humans and agents.",
  get_asset_library_item: "Resolve one library item and its README, preview, sprite sheet, and variants.",
  get_asset_preset: "Resolve a ready-to-compose scene preset and its recommended MCP tools.",
  get_color_stats: "Return JSON color usage statistics for one flattened frame.",
  get_composite_pixel: "Read one RGBA pixel from the visible flattened composite.",
  get_composite_rect: "Read a visible flattened composite region as JSON.",
  get_palette: "Return the active sprite palette as a JSON color array.",
  get_pixel_color: "Read one RGBA pixel from a cel.",
  get_pixels_rect: "Read a rectangular RGBA region from a cel as JSON.",
  get_sprite_info: "Read sprite dimensions, color mode, frame durations, layers, and tags as JSON.",
  get_tile_at: "Read the tile index at a tilemap grid coordinate.",
  get_tilemap_info: "Read tile size, tileset count, and map dimensions.",
  get_tools_by_folder: "List concise tools in one folder. Use a parent folder to inspect its subfolders.",
  get_tools_list: "List tool folders and counts. Use this before loading a tool folder.",
  get_tools_search: "Search a compact subset of tools by name, description, or folder to reduce context usage.",
  harmonize_asset_palette: "Harmonize a sprite palette toward an accent color with bounded deterministic output.",
  import_image_as_layer: "Import an image into a named layer and frame, creating the layer when it does not exist.",
  inspect_animation_quality: "Audit animation frames, timing, palette drift, movement bounds, and loop seams.",
  inspect_asset_batch: "Inspect up to 32 sprites in one compact quality report.",
  inspect_asset_bundle: "Inspect one asset and return quality violations and recommendations in one compact response.",
  inspect_reference: "Analyze reference dimensions, dominant colors, contrast, edges, and transparency.",
  inspect_sprite_geometry: "Inspect per-frame alpha bounds, connected components, baseline, and bottom-center pivots for scene placement.",
  invert_colors: "Apply Aseprite native color inversion.",
  list_convolution_matrices: "List the built-in convolution matrices supported by Aseprite.",
  list_palette_presets: "List built-in retro palette presets.",
  list_slices: "List slice bounds, centers, and pivots as JSON.",
  list_text_fonts: "List discoverable TrueType and OpenType fonts.",
  measure_text: "Measure a text run without changing a sprite.",
  merge_layer_down: "Merge a layer into the layer below it.",
  move_region: "Move a rectangular region within a cel, clearing its source.",
  normalize_sprite: "Crop raster frames to shared alpha bounds, add padding, and write deterministic pivot metadata without overwriting the source.",
  offset_cel_positions: "Offset cel positions across a frame range.",
  oscillate_cel_positions: "Apply sine-wave position offsets to cels across frames.",
  outline_native: "Apply Aseprite native outline (inside/outside, circle/square) to a selected layer and frame.",
  plan_asset_scene: "Plan ordered scene layers from selected library assets without generating files.",
  propagate_cels: "Copy selected layer cels from one source frame across a frame range.",
  propagate_frame_to_range: "Propagate all source-frame cels to a frame range.",
  quantize_to_palette: "Snap opaque pixels to the nearest color in the active palette.",
  recommend_asset_scene: "Recommend explainable library assets for a deterministic scene composition.",
  remap_colors_in_cel_range: "Remap explicit RGB colors across a layer frame range while preserving alpha.",
  rename_layer: "Rename a named layer.",
  render_onion_skin: "Render neighboring animation frames as translucent onion-skin ghosts into a PNG.",
  reorder_layer: "Move a layer to a one-based stack position.",
  replace_color: "Replace a cel color while preserving alpha and allowing channel tolerance.",
  resize_canvas: "Resize the sprite canvas and its content.",
  rotate_layer: "Rotate a layer cel 90, 180, or 270 degrees clockwise.",
  run_asset_quality_gate: "Check pixel-art quality (colors, isolated pixels, contrast, banding) before export.",
  run_asset_recipe: "Run or preview one compact asset recipe (pixel art, GIF, or atlas).",
  run_lua_script: "Run a bounded trusted Aseprite script as an escape hatch; dedicated tools are preferred.",
  server_capabilities: "Return server version, architecture, tool count, and the full tool list.",
  set_cel_opacity: "Set one cel opacity from 0 to 255.",
  set_cel_position: "Set one cel position, optionally creating it from a source cel.",
  set_color_mode: "Convert a sprite to RGB, grayscale, or indexed color mode.",
  set_frame: "Set the active animation frame by one-based index.",
  set_frame_duration: "Set one animation frame duration in milliseconds.",
  set_frame_duration_all: "Set all animation frame durations in milliseconds.",
  set_layer: "Set the active layer by name, optionally creating it.",
  set_layer_blend_mode: "Set a layer blend mode supported by Aseprite.",
  set_layer_opacity: "Set a named layer opacity from 0 to 255.",
  set_layer_visibility: "Set a named layer visibility.",
  set_onion_skin: "Validate onion-skin settings for batch workflows; UI-only settings are reported explicitly.",
  set_palette: "Apply a controlled hexadecimal palette to a document.",
  set_slice_center: "Set a slice 9-patch center rectangle.",
  set_slice_pivot: "Set a slice pivot point.",
  set_tag: "Create or update an animation tag.",
  set_tiles: "Place tile indices on a tilemap frame by grid coordinates.",
  start_asset_job: "Start an asynchronous batch asset job and return its job id without blocking.",
  start_preview_server: "Serve a validated local directory over HTTP for visual asset preview.",
  stop_preview_server: "Stop a preview server started by this MCP process.",
  suggest_enhancement_plan: "Inspect one image and return a deterministic, non-destructive enhancement plan for review.",
  summarize_asset_library: "Return compact library categories and preset navigation metadata.",
  tween_cel_opacity_eased: "Tween cel opacity from 0 to 255 across frames with easing.",
  tween_cel_positions: "Tween cel positions linearly across a frame range.",
  tween_cel_positions_eased: "Tween cel positions across frames with deterministic easing.",
  tween_cel_scale_eased: "Scale a source cel across frames with easing and a stable anchor.",
  upscale_pixel_art: "Upscale sprites with deterministic nearest-neighbor pixels and preserved transparency.",
  validate_scene: "Validate required layers and the requested frame range before export.",
};

function folderFor(name: string): string {
  const folder = TOOL_FOLDERS[name];
  if (!folder) throw new Error(`Tool catalog has no explicit folder assignment for tool: ${name}`);
  return folder;
}

function descriptionFor(name: string): string {
  const description = TOOL_DESCRIPTIONS[name];
  if (!description) throw new Error(`Tool catalog has no explicit description for tool: ${name}`);
  return description;
}

function folderSummary(descriptors: ToolDescriptor[]): ToolFolderSummary[] {
  const counts = new Map<string, number>();
  for (const descriptor of descriptors) counts.set(descriptor.folder, (counts.get(descriptor.folder) ?? 0) + 1);
  const folders = [...counts.keys()].sort();
  return folders.map((folder) => ({
    folder,
    toolCount: counts.get(folder) ?? 0,
    children: folders.filter((candidate) => candidate !== folder && candidate.startsWith(`${folder}/`) && !candidate.slice(folder.length + 1).includes("/")),
  }));
}

export class ToolCatalogService {
  private readonly descriptors: ToolDescriptor[];

  public constructor(toolNames: readonly string[]) {
    this.descriptors = [...new Set(toolNames)].sort().map((name) => ({ name, folder: folderFor(name), description: descriptionFor(name) }));
  }

  public list(includeTools = false): ToolCatalogList {
    return { toolCount: this.descriptors.length, folders: folderSummary(this.descriptors), ...(includeTools ? { tools: this.descriptors.map(({ name }) => name) } : {}) };
  }

  public byFolder(folder: string): ToolDescriptor[] {
    const normalized = folder.trim().toLowerCase().replaceAll("\\", "/").replace(/^\/+|\/+$/g, "");
    return this.descriptors.filter((descriptor) => descriptor.folder === normalized || descriptor.folder.startsWith(`${normalized}/`));
  }

  public search(query: string, limit = 20): ToolDescriptor[] {
    const normalized = query.trim().toLowerCase();
    if (!normalized) return [];
    const boundedLimit = Number.isInteger(limit) ? Math.max(1, Math.min(100, limit)) : 20;
    return this.descriptors.filter((descriptor) => `${descriptor.name} ${descriptor.description} ${descriptor.folder}`.toLowerCase().includes(normalized)).slice(0, boundedLimit);
  }
}
